export const CARDS = [
    {
        name:'c2',
        weight:2,
        classname:'c2'
    },
    {
        name:'c3',
        weight:3,
        classname:'c3'
    },
    {
        name:'c4',
        weight:4,
        classname:'c4'
    },
    {
        name:'c5',
        weight:5,
        classname:'c5'
    },
    {
        name:'c6',
        weight:6,
        classname:'c6'
    },
    {
        name:"c7",
        weight:7,
        classname:"c7"
    },
    {
        name:'c8',
        weight:8,
        classname:'c8'
    },
    {
        name:'c9',
        weight:9,
        classname:'c9'
    },
    {
        name:'c10',
        weight:10,
        classname:'c10'
    },
    {
        name:'cj',
        weight:'j',
        classname:'cj'
    },
    {
        name:'cq',
        weight:'q',
        classname:'cq'
    },
    {
        name:'ck',
        weight:'k',
        classname:'ck'
    },
    {
        name:'ca',
        weight:'a',
        classname:'ca'
    },
    {
        name:'h2',
        weight:2,
        classname:'h2'
    },
    {
        name:'h3',
        weight:3,
        classname:'h3'
    },
    {
        name:'h4',
        weight:4,
        classname:'h4'
    },
    {
        name:'h5',
        weight:5,
        classname:'h5'
    },
    {
        name:'h6',
        weight:6,
        classname:'h6'
    },
    {
        name:'h7',
        weight:7,
        classname:'h7'
    },
    {
        name:'h8',
        weight:8,
        classname:'h8'
    },
    {
        name:'h9',
        weight:9,
        classname:'h9'
    },
    {
        name:'h10',
        weight:10,
        classname:'h10'
    },
    {
        name:'hj',
        weight:'j',
        classname:'hj'
    },
    {
        name:'hq',
        weight:'q',
        classname:'hq'
    },
    {
        name:'hk',
        weight:'k',
        classname:'hk'
    },
    {
        name:'ha',
        weight:'a',
        classname:'ha'
    },
    {
        name:'p2',
        weight:2,
        classname:'p2'
    },
    {
        name:'p3',
        weight:3,
        classname:'p3'
    },
    {
        name:'p4',
        weight:4,
        classname:'p4'
    },
    {
        name:'p5',
        weight:5,
        classname:'p5'
    },
    {
        name:'p6',
        weight:6,
        classname:'p6'
    },
    {
        name:'p7',
        weight:7,
        classname:'p7'
    },
    {
        name:'p8',
        weight:8,
        classname:'p8'
    },
    {
        name:'p9',
        weight:9,
        classname:'p9'
    },
    {
        name:'p10',
        weight:10,
        classname:'p10'
    },
    {
        name:'pj',
        weight:'j',
        classname:'pj'
    },
    {
        name:'pq',
        weight:'q',
        classname:'pq'
    },
    {
        name:'pk',
        weight:'k',
        classname:'pk'
    },
    {
        name:'pa',
        weight:'a',
        classname:'pa'
    },
        {
        name:'r2',
        weight:2,
        classname:'r2'
    },
    {
        name:'r3',
        weight:3,
        classname:'r3'
    },
    {
        name:'r4',
        weight:4,
        classname:'r4'
    },
    {
        name:'r5',
        weight:5,
        classname:'r5'
    },
    {
        name:'r6',
        weight:6,
        classname:'r6'
    },
    {
        name:'r7',
        weight:7,
        classname:'r7'
    },
    {
        name:'r8',
        weight:8,
        classname:'r8'
    },
    {
        name:'r9',
        weight:9,
        classname:'r9'
    },
    {
        name:'r10',
        weight:10,
        classname:'r10'
    },
    {
        name:'rj',
        weight:'j',
        classname:'rj'
    },
    {
        name:'rq',
        weight:'q',
        classname:'rq'
    },
    {
        name:'rk',
        weight:'k',
        classname:'rk'
    },
    {
        name:'ra',
        weight:'a',
        classname:'ra'
    },
    
    
]   